apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki
  namespace: wiki
  labels:
    app: wiki
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiki
      tier: backend
  template:
    metadata:
      labels:
        app: wiki
        tier: backend
    spec:
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: wiki-pvc
          persistentVolumeClaim:
            claimName: wiki-pvc
        - name: localsettings-configmap
          configMap:
            name: localsettings-configmap
      initContainers:
        # Sets the 777 permissions on the images folder
        - name: images-folder-permissions
          image: alpine:latest
          command: ['sh', '-c', 'chmod -R 777 /images']
          volumeMounts:
            - name: wiki-pvc
              mountPath: /images
      containers:
        - image: docker.io/kallepan/wiki:latest
          imagePullPolicy: Always
          name: wiki
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            httpGet:
              path: /index.php/Hauptseite
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /index.php/Hauptseite
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: wiki-pvc
              mountPath: /var/www/html/images
            - name: localsettings-configmap
              mountPath: /var/www/html/LocalSettings.php
              subPath: LocalSettings.php
          securityContext:
            allowPrivilegeEscalation: false